name: Run Pattini

on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - '*'
  

jobs:
  branch-creation-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.event.created
    steps:
      - name: Extract Issue Number
        id: extract-issue-number
        run: echo "::set-output name=issue_number::$(echo $GITHUB_REF | awk -F/ '{print $3}')"

      - name: Pattini app
        uses: w3hc/pattini@vTest
        with:
          ISSUE_NUMBER: ${{ steps.extract-issue-number.outputs.issue_number }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
          PRIVATE_KEY: ${{ secrets.WALLET_OWNER_PRIVATE_KEY }}
          ACTION: ${{ github.event_name }}

  on-merge-pull-request:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged
    steps:
      - name: Pattini app
        uses: w3hc/pattini@vTest
        with:
          ISSUE_NUMBER: null
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
          PRIVATE_KEY: ${{ secrets.WALLET_OWNER_PRIVATE_KEY }}
          ACTION: ${{ github.event_name }}


