name: Run Pattini

on:
  push:
    branches: "*"

jobs:
  on_merge_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Pattini app
        uses: w3hc/pattini@v0.0.3 
        with:
          parameter1: '12'
          parameter2: '0x13'
